name: Run commands when issues are labeled or comments added
on:
  issues:
    types: [labeled, opened]
  issue_comment:
    types: [created]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: 'JacksonKearl/vscode-triage-github-actions'
          ref: v42
      - name: Install Actions
        run: npm install --production
      - name: Run Commands
        uses: ./commands
        with:
          token: ${{secrets.RPEO_TOKEN}}
